const KEY="tradevision_v2";
const demo={settings:{email:"",senderName:"TradeVision AI",defaultSource:"BYMADATA Open",staleHours:24},portfolios:[
{id:"P001",name:"Cartera Crecimiento",horizon:"MP",risk:"Moderada",strategy:"MA, RSI",shortTrade:false,assets:[
{ticker:"AAPL",name:"Apple CEDEAR",qty:45,price:12500,cost:10900,currency:"ARS",source:"Demo",updatedAt:"2026-07-20T12:00:00"},
{ticker:"SPY",name:"ETF S&P 500",qty:18,price:35200,cost:33000,currency:"ARS",source:"Demo",updatedAt:"2026-07-20T12:00:00"}]},
{id:"P002",name:"Cartera DCA",horizon:"DCA",risk:"Conservadora",strategy:"DCA",shortTrade:false,assets:[
{ticker:"QQQ",name:"ETF Nasdaq 100",qty:10,price:28700,cost:27000,currency:"ARS",source:"Demo",updatedAt:"2026-07-20T12:00:00"}]}],
movements:[{date:"2026-07-05",portfolio:"P002",type:"Depósito",ticker:"-",qty:0,amount:400000,currency:"ARS"}],
alerts:[{date:"2026-07-20",level:"Info",ticker:"AAPL",horizon:"MP",text:"Alerta demostrativa inicial."}]};
let state=load(),modalAction=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(demo)}catch{return structuredClone(demo)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function money(n,c="ARS"){return new Intl.NumberFormat("es-AR",{style:"currency",currency:["MEP","CCL"].includes(c)?"USD":c,maximumFractionDigits:2}).format(+n||0)}
function pnl(a){return a.cost?((a.price-a.cost)/a.cost)*100:0}
function val(a){return a.qty*a.price}
function assets(){return state.portfolios.flatMap(p=>p.assets.map((a,i)=>({...a,pid:p.id,pname:p.name,horizon:p.horizon,index:i})))}
function stale(a){if(!a.updatedAt)return true;return (Date.now()-new Date(a.updatedAt).getTime())/36e5>+state.settings.staleHours}
const views={dashboard:["Dashboard","Resumen general"],portfolios:["Carteras","Administración de carteras"],prices:["Cotizaciones","Carga manual y CSV"],movements:["Movimientos","Bitácora de operaciones"],alerts:["Alertas","Evaluación y correo"],settings:["Configuración","Preferencias generales"]};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.getElementById(b.dataset.view).classList.add("active");title.textContent=views[b.dataset.view][0];subtitle.textContent=views[b.dataset.view][1]});
function render(){
 const aa=assets(),invested=aa.reduce((s,a)=>s+val(a),0),cost=aa.reduce((s,a)=>s+a.qty*a.cost,0),gp=cost?(invested-cost)/cost*100:0;
 metrics.innerHTML=[["Carteras",state.portfolios.length],["Activos",aa.length],["Valor",money(invested)],["Resultado",gp.toFixed(2)+"%"]].map((x,i)=>`<div class="metric"><small>${x[0]}</small><strong class="${i===3?(gp>=0?"positive":"negative"):""}">${x[1]}</strong></div>`).join("");
 const total=state.portfolios.reduce((s,p)=>s+p.assets.reduce((q,a)=>q+val(a),0),0)||1;
 bars.innerHTML=state.portfolios.map(p=>{const v=p.assets.reduce((s,a)=>s+val(a),0),pc=v/total*100;return `<div class="barrow"><span>${p.id}</span><div class="bar"><span style="width:${pc}%"></span></div><b>${pc.toFixed(1)}%</b></div>`}).join("");
 recentAlerts();
 summary.innerHTML=`<thead><tr><th>Cartera</th><th>Activo</th><th>Cantidad</th><th>Precio</th><th>Valor</th><th>G/P</th></tr></thead><tbody>${aa.map(a=>`<tr><td>${a.pid}</td><td>${a.ticker}</td><td>${a.qty}</td><td>${money(a.price,a.currency)}</td><td>${money(val(a),a.currency)}</td><td class="${pnl(a)>=0?"positive":"negative"}">${pnl(a).toFixed(2)}%</td></tr>`).join("")}</tbody>`;
 portfolioList();
 priceTable();
 movementTable();
 alertList();
 email.value=state.settings.email||"";document.getElementById("sender-name").value=state.settings.senderName||"TradeVision AI";document.getElementById("default-source").value=state.settings.defaultSource||"BYMADATA Open";document.getElementById("stale-hours").value=state.settings.staleHours||24;
}
function recentAlerts(){document.getElementById("recent-alerts").innerHTML=state.alerts.slice(0,5).map(a=>`<p><b>${a.level}</b> · ${a.ticker||"-"}<br><small>${a.date}</small> ${a.text}</p>`).join("")||"<p>Sin alertas.</p>"}
function portfolioList(){document.getElementById("portfolio-list").innerHTML=state.portfolios.map(p=>`<article class="portfolio"><div class="portfolio-head"><div><h3>${p.name}</h3><small>${p.id}</small><div class="tags"><span class="tag">${p.horizon}</span><span class="tag">${p.risk}</span><span class="tag">${p.strategy}</span>${p.shortTrade?'<span class="tag">TC</span>':""}</div></div><div><button class="small" onclick="addAsset('${p.id}')">+ Activo</button> <button class="small secondary" onclick="delPortfolio('${p.id}')">Eliminar</button></div></div><div class="table"><table><thead><tr><th>Ticker</th><th>Nombre</th><th>Cantidad</th><th>Precio</th><th>Costo</th><th>G/P</th><th></th></tr></thead><tbody>${p.assets.map((a,i)=>`<tr><td>${a.ticker}</td><td>${a.name}</td><td>${a.qty}</td><td>${money(a.price,a.currency)}</td><td>${money(a.cost,a.currency)}</td><td class="${pnl(a)>=0?"positive":"negative"}">${pnl(a).toFixed(2)}%</td><td><button class="small secondary" onclick="delAsset('${p.id}',${i})">×</button></td></tr>`).join("")}</tbody></table></div></article>`).join("")}
function priceTable(){document.getElementById("prices-table").innerHTML=`<thead><tr><th>Ticker</th><th>Carteras</th><th>Precio</th><th>Moneda</th><th>Fuente</th><th>Actualización</th><th>Estado</th></tr></thead><tbody>${[...new Set(assets().map(a=>a.ticker))].map(t=>{const rows=assets().filter(a=>a.ticker===t),a=rows[0];return `<tr><td><b>${t}</b></td><td>${rows.map(x=>x.pid).join(", ")}</td><td>${money(a.price,a.currency)}</td><td>${a.currency}</td><td>${a.source||"-"}</td><td>${a.updatedAt?new Date(a.updatedAt).toLocaleString("es-AR"):"-"}</td><td class="${stale(a)?"neutral":"positive"}">${stale(a)?"Desactualizado":"Vigente"}</td></tr>`}).join("")}</tbody>`}
function movementTable(){document.getElementById("movements-table").innerHTML=`<thead><tr><th>Fecha</th><th>Cartera</th><th>Tipo</th><th>Ticker</th><th>Cantidad</th><th>Monto</th><th>Moneda</th></tr></thead><tbody>${state.movements.map(m=>`<tr><td>${m.date}</td><td>${m.portfolio}</td><td>${m.type}</td><td>${m.ticker}</td><td>${m.qty}</td><td>${money(m.amount,m.currency)}</td><td>${m.currency}</td></tr>`).join("")}</tbody>`}
function alertList(){document.getElementById("alerts-list").innerHTML=state.alerts.map(a=>`<article class="card"><h3>${a.level} · ${a.ticker||"-"}</h3><p>${a.date} · ${a.horizon||"-"}</p><p>${a.text}</p></article>`).join("")}
function openModal(titleText,fields,fn){document.getElementById("modal-title").textContent=titleText;document.getElementById("modal-body").innerHTML=fields.map(f=>`<label class="field ${f.span?"span2":""}">${f.label}${f.type==="select"?`<select id="f-${f.id}">${f.options.map(o=>`<option value="${o}">${o}</option>`).join("")}</select>`:`<input id="f-${f.id}" type="${f.type||"text"}" value="${f.value||""}" step="${f.step||"any"}">`}</label>`).join("");modalAction=()=>{let d={};fields.forEach(f=>d[f.id]=document.getElementById("f-"+f.id).value);fn(d)};modal.showModal()}
document.getElementById("modal-form").addEventListener("submit",e=>{if(e.submitter?.id==="modal-save"){e.preventDefault();modalAction?.();modal.close()}});
document.getElementById("new-portfolio").onclick=()=>openModal("Nueva cartera",[{id:"name",label:"Nombre",span:true},{id:"horizon",label:"Horizonte",type:"select",options:["CP","MP","LP","DCA"]},{id:"risk",label:"Riesgo",type:"select",options:["Conservadora","Moderada","Agresiva"]},{id:"strategy",label:"Indicadores",value:"MA, RSI"},{id:"tc",label:"Trade corto",type:"select",options:["No","Sí"]}],d=>{let id="P"+String(state.portfolios.length+1).padStart(3,"0");state.portfolios.push({id,name:d.name||id,horizon:d.horizon,risk:d.risk,strategy:d.strategy,shortTrade:d.tc==="Sí",assets:[]});save()});
window.addAsset=pid=>openModal("Agregar activo",[{id:"ticker",label:"Ticker"},{id:"name",label:"Nombre"},{id:"qty",label:"Cantidad",type:"number"},{id:"price",label:"Precio",type:"number"},{id:"cost",label:"Costo promedio",type:"number"},{id:"currency",label:"Moneda",type:"select",options:["ARS","USD","MEP","CCL"]},{id:"source",label:"Fuente",value:state.settings.defaultSource}],d=>{state.portfolios.find(p=>p.id===pid).assets.push({...d,ticker:d.ticker.toUpperCase(),qty:+d.qty,price:+d.price,cost:+d.cost,updatedAt:new Date().toISOString()});save()});
window.delAsset=(pid,i)=>{if(confirm("¿Eliminar activo?")){state.portfolios.find(p=>p.id===pid).assets.splice(i,1);save()}};
window.delPortfolio=pid=>{if(confirm("¿Eliminar cartera?")){state.portfolios=state.portfolios.filter(p=>p.id!==pid);save()}};
document.getElementById("quick-price").onclick=()=>openModal("Actualizar cotización",[{id:"ticker",label:"Ticker"},{id:"price",label:"Precio",type:"number"},{id:"currency",label:"Moneda",type:"select",options:["ARS","USD","MEP","CCL"]},{id:"date",label:"Fecha y hora",type:"datetime-local",value:new Date().toISOString().slice(0,16)},{id:"source",label:"Fuente",value:state.settings.defaultSource}],updatePrice);
function updatePrice(d){let found=0;state.portfolios.forEach(p=>p.assets.forEach(a=>{if(a.ticker.toUpperCase()===d.ticker.toUpperCase()){a.price=+d.price;a.currency=d.currency;a.source=d.source;a.updatedAt=new Date(d.date).toISOString();found++}}));if(!found)return alert("No se encontró ese ticker.");save()}
document.getElementById("csv-file").onchange=async e=>{const text=await e.target.files[0].text();const lines=text.split(/\r?\n/).filter(Boolean);let start=lines[0].toLowerCase().includes("ticker")?1:0,count=0;for(let i=start;i<lines.length;i++){const [ticker,price,currency,date,source]=lines[i].split(",").map(x=>x.trim());if(!ticker||!price)continue;state.portfolios.forEach(p=>p.assets.forEach(a=>{if(a.ticker.toUpperCase()===ticker.toUpperCase()){a.price=+price;a.currency=currency||a.currency;a.updatedAt=date?new Date(date).toISOString():new Date().toISOString();a.source=source||state.settings.defaultSource;count++}}))}save();alert(`Se actualizaron ${count} posiciones.`);e.target.value=""};
document.getElementById("download-template").onclick=()=>download("plantilla_precios.csv","ticker,precio,moneda,fecha,fuente\nAAPL,18250,ARS,2026-07-20,BYMADATA Open\n","text/csv");
document.getElementById("new-movement").onclick=()=>openModal("Registrar movimiento",[{id:"date",label:"Fecha",type:"date",value:new Date().toISOString().slice(0,10)},{id:"portfolio",label:"Cartera",type:"select",options:state.portfolios.map(p=>p.id)},{id:"type",label:"Tipo",type:"select",options:["Compra","Venta","Depósito","Extracción"]},{id:"ticker",label:"Ticker",value:"-"},{id:"qty",label:"Cantidad",type:"number"},{id:"amount",label:"Monto",type:"number"},{id:"currency",label:"Moneda",type:"select",options:["ARS","USD","MEP","CCL"]}],d=>{state.movements.unshift({...d,qty:+d.qty,amount:+d.amount});save()});
document.getElementById("evaluate").onclick=()=>{evaluate();save();alert("Señales evaluadas.")};
function evaluate(){const today=new Date().toISOString().slice(0,10),out=[];state.portfolios.forEach(p=>p.assets.forEach(a=>{let perf=pnl(a),level="Info",text=`${a.ticker}: sin señal concluyente con la información manual disponible.`;if(perf<=-10){level="Stop loss";text=`${a.ticker}: pérdida estimada ${perf.toFixed(2)}%. Revisar mínimo anual y estrategia.`}else if(perf>=8){level="Compra / mantener";text=`${a.ticker}: rendimiento ${perf.toFixed(2)}%. Validar cruce de medias ${p.horizon}.`}out.push({date:today,level,ticker:a.ticker,horizon:p.horizon,text:`${text} Cartera ${p.id}.`})}));state.alerts=[...out,...state.alerts].slice(0,50);return out}
async function sendEmail(test=false){const recipient=state.settings.email;if(!recipient)return setStatus(false,"Configurá primero el email receptor.");let list=test?[{level:"Prueba",ticker:"TEST",horizon:"-",text:"El envío de TradeVision AI mediante Resend funciona correctamente."}]:evaluate();save();setStatus(true,"Enviando…");try{const r=await fetch("/.netlify/functions/send-alerts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:recipient,senderName:state.settings.senderName,alerts:list,test})});const data=await r.json();if(!r.ok)throw new Error(data.error||"No se pudo enviar");setStatus(true,`Correo enviado a ${recipient}. ID: ${data.id||"confirmado"}`)}catch(err){setStatus(false,err.message)}}
document.getElementById("send-alerts").onclick=()=>sendEmail(false);document.getElementById("test-email").onclick=()=>sendEmail(true);
function setStatus(ok,msg){document.getElementById("email-status").innerHTML=`<div class="status ${ok?"ok":"err"}">${msg}</div>`}
document.getElementById("save-settings").onclick=()=>{state.settings={email:document.getElementById("email").value.trim(),senderName:document.getElementById("sender-name").value.trim(),defaultSource:document.getElementById("default-source").value.trim(),staleHours:+document.getElementById("stale-hours").value};save();alert("Configuración guardada.")};
document.getElementById("backup").onclick=()=>download("tradevision-v2-backup.json",JSON.stringify(state,null,2),"application/json");
document.getElementById("export-csv").onclick=()=>download("movimientos.csv",["fecha,cartera,tipo,ticker,cantidad,monto,moneda",...state.movements.map(m=>[m.date,m.portfolio,m.type,m.ticker,m.qty,m.amount,m.currency].join(","))].join("\n"),"text/csv");
function download(name,text,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
render();